# GitHub Pages Jekyll configuration
# This file enables GitHub Pages to serve static files properly

# Basic settings
title: "Mountain Wedding - Tye & Louise"
description: "Join Tye & Louise for their mountain wedding celebration in Crested Butte, Colorado"

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from processing
exclude:
  - README.md
  - package.json
  - build.js
  - server.js
  - node_modules/
  - .git/
  - .github/

# Include files that start with underscore or dot
include:
  - _headers
  - _redirects

# Custom headers for performance
webrick:
  headers:
    "*.css": "Cache-Control: public, max-age=31536000"
    "*.js": "Cache-Control: public, max-age=31536000"
    "*.woff2": "Cache-Control: public, max-age=31536000"
    "*.jpg": "Cache-Control: public, max-age=31536000"
    "*.png": "Cache-Control: public, max-age=31536000"
    "*.svg": "Cache-Control: public, max-age=31536000"