# Wedding Site Configuration
# Edit this file to customize your wedding website

couple:
  names: "Tye & Louise"

date:
  display: "09.18.2026"
  iso: "2026-09-18T16:00:00"

theme:
  primary: "#781b12"         # Deep burgundy - warm and sophisticated
  font: "Montserrat"         # Clean mountain-appropriate font

  # Light theme - warm and elegant with your colors
  text_primary: "#2c1810"    # Very dark brown for better readability than pure black
  text_secondary: "#781b12"  # Deep burgundy for secondary content
  text_muted: "#41512d"      # Deep olive for muted text
  text_light: "#ffffff"      # Pure white for light text

  # Dark theme - burgundy background with warm text palette
  dark:
    text_primary: "#ffffff"  # Pure white for main text - maximum contrast on burgundy
    text_secondary: "#f3912b" # Warm orange for headings and accents
    text_muted: "#e5e1e3"    # Light warm gray for subtle text
    text_light: "#000000"    # Pure black for contrast elements

  # CSS variable mappings for the website
  css_vars:
    light:
      primary: "#8B4513"
      secondary: "#f3912b"
      accent: "#e5e1e3"
      text_dark: "#2c1810"
      text_secondary: "#781b12"
      text_muted: "#41512d"
      text_light: "#ffffff"
      bg_light: "#ffffff"
      bg_dark: "#e5e1e3"
      mountain_gradient: "linear-gradient(135deg, #781b12 0%, #f3912b 50%, #e5e1e3 100%)"
    dark:
      text_dark: "#F8F8F8"
      text_secondary: "#f3912b"
      text_muted: "#CCCCCC"
      text_light: "#000000"
      bg_light: "#1C1C1C"
      bg_dark: "#2A2A2A"
      mountain_gradient: "linear-gradient(135deg, #2C3E50 0%, #34495E 50%, #4A6741 100%)"

  # Color scheme for cost indicators
  cost_colors:
    cost_1: "#22c55e"  # $ - green
    cost_2: "#eab308"  # $$ - yellow
    cost_3: "#f97316"  # $$$ - orange
    cost_4: "#ef4444"  # $$$$ - red

  # Color scheme for availability indicators
  availability_colors:
    excellent: "#22c55e"
    good: "#eab308"
    limited: "#f97316"

# Navigation sections - customize order and visibility
sections:
  - id: home
    name: "Home"
    enabled: true
    
  - id: details
    name: "Schedule"
    enabled: true
    
  - id: timeline
    name: "Our Story"
    enabled: true
    
  - id: travel
    name: "Travel"
    enabled: true
    
  - id: accommodations
    name: "Hotels"
    enabled: true
    
  - id: registry
    name: "Registry"
    enabled: true
    
  - id: gallery
    name: "Gallery"
    enabled: false
    
  - id: rsvp
    name: "RSVP"
    enabled: true

# Event details
ceremony:
  time: "September 18th 4-10 PM"
  venue: "Mountain Wedding Garden"
  maps_url: "https://www.google.com/maps/search/?api=1&query=Mountain+Wedding+Garden+Crested+Butte+CO"
  dress_code:
    title: "Mountain Formal"
    description: "the venue is indoor-outdoor, coats and/or layers strongly recommended!"

reception:
  time: "September 19th 6-12 PM"
  venue: "Public House"
  maps_url: "https://maps.app.goo.gl/xVtrt1GBFYv4ygtH7"
  dress_code:
    title: "Western Cocktail"
    description: "for the Historic Saloon built in 1882!"

# Detailed dress code information
dress_code:
  intro: "Bring warm clothes!"
  sections:
    - title: "Mountain Formal"
      description: "formal attire in nature inspired colors and textures"
    - title: "Western Cocktail" 
      description: "dressy Western, lean into the mountain vibe and have fun with it!"
  pinterest:
    url: "https://pin.it/2MKZfWCt5"
    text: "Pinterest Board"
    description: "for inspiration"

# Timeline section (optional)
timeline:
  events:
    - date: "Winter 2016"
      title: "Our First Trip"
      description: "We find cheap flights to Scandinavia and go on our first trip, as friends!"
      images:
        - "./images/LouiseTyeCopenhagen.webp"

    - date: "Summer 2017"
      title: "Dating Begins"
      description: "Road trips and exploring the great outdoors together as an official couple"
      images:
        - "./images/LouiseTyeCornPalace.webp"
        - "./images/roadtrip2017.webp"
        - "./images/SouthDakota.webp"

    - date: "Winter 2018"
      title: "Louise's first time in Aspen"
      description: "Hitting the slopes in Aspen - discovering our love for the mountains"
      images:
        - "./images/louise_aspen.webp"

    - date: "Summer 2020"
      title: "Work from Anywhere"
      description: "We spend the summer in Aspen working from home"
      images:
        - "./images/LouiseTye4Passloup.webp"
        - "./images/FourPassLoopVert.webp"
        - "./images/GreatSandDunes.webp"

    - date: "Aug 2021"
      title: "Moving in Together in Raleigh"
      description: "Moving in together and making a space that's truly ours"
      images:
        - "./images/move_in.webp"
        - "./images/twin_oaks.webp"

    - date: "Nov 2022"
      title: "Getting Poppy"
      description: "Thanksgiving gave us more to be thankful for than expected this year"
      images:
        - "./images/poppy2.webp"
        - "./images/poppy1.webp"

    - date: "2022-2024"
      title: "Post Graduation Fun"
      description: "Louise finishes grad school and opens a new world of adventures, on PTO!"
      images:
        - "./images/LouiseTyeVietnam.webp"
        - "./images/LouiseTyeBoone.webp"
        - "./images/LouiseTyeBeach.webp"

    - date: "December 2024"
      title: "The Proposal"
      description: "A surprise proposal at the Maroon Bells"
      images:
        - "./images/Proposal.webp"
        - "./images/engagement.webp"

    - date: "Summer 2025"
      title: "Move to Durham"
      description: "Compare to our previous apartment photo to see how much our Bird of Paradise has grown alongside us"
      images:
        - "./images/Apartment.webp"

    - date: "Now - Infinity"
      title: "Adventure Awaits"
      description: "Here's to a lifetime of laughter, love, and new adventures!!!"
      images:
        - "./images/LouiseTyeOktoberfest.webp"
        - "./images/LouiseTyeIceland.webp"

# Travel Information
travel:
  airports:
    - name: "Gunnison-Crested Butte Regional Airport"
      code: "GUC"
      distance_miles: 28
      drive_time: "30 minutes"
      cost_range: "$$$"
      flight_availability: "Limited"
      description: "Closest airport to Crested Butte. For these dates, only three daily flights on United from Denver. Book early! 
        There is a free bus from the airport to Downtown."
      airlines: ["United (3 daily flights from DEN)"]
      
    - name: "Montrose Regional Airport"
      code: "MTJ"
      distance_miles: 65
      drive_time: "1 hour 30 minutes"
      cost_range: "$$"
      flight_availability: "Good"
      description: "Year-round flights with good availability. 
        Scenic drive with sightseeing opportunity for the Black Canyon of the Gunnison National Park nearby!!"
      airlines: ["United", "American", "Delta", "Alaska"]
      
    - name: "Denver International Airport"
      code: "DEN"
      distance_miles: 230
      drive_time: "4 hours"
      cost_range: "$"
      flight_availability: "Excellent"
      description: "Most flight options and best prices. Beautiful mountain drive but long journey."
      airlines: ["All major airlines"]
      
  driving_tips:
    - "Rental car recommended for mountain driving and local flexibility"
    - "There is a free bus available between Crested Butte Downtown and the Mountain Village - <a href=\"https:\\www.mtnexp.org\">Mountain Express</a>"
    - "Be aware that gas stations are extremely limited in some parts of Colorado"

# Accommodations
hotels:
  - name: "Vaquera House"
    rate: "$$$"
    description: "Luxury boutique hotel in downtown Crested Butte with modern amenities and stunning mountain views. Walking distance to restaurants and shops."
    link: "https://vaquerahouse.com/"
    maps_url: "https://maps.app.goo.gl/xU36CGnuC8xcDRLt5"

  - name: "Elk Mountain Lodge"
    rate: "$$"
    description: "Cozy mountain lodge offering comfortable accommodations with rustic charm. Features heated pool, hot tub, and continental breakfast."
    link: "https://www.elkmountainlodge.com"
    maps_url: "https://www.google.com/maps/search/?api=1&query=Elk+Mountain+Lodge+Crested+Butte"

  - name: "Old Town Inn"
    rate: "$"
    description: "Historic inn in the heart of Crested Butte offering affordable rooms with authentic mountain character. Perfect for budget-conscious travelers."
    link: "https://www.oldtowninn.net"
    maps_url: "https://www.google.com/maps/search/?api=1&query=Old+Town+Inn+Crested+Butte"

# Registry
registry:
  message: "Your presence at our wedding is the greatest gift of all, however if you'd like to honor us with a gift we've provided registry options below. We're thankful to have most of what we need, so honeymoon fund is preferred."
  stores:
    - name: "Honeymoon Fund"
      description: "Help us create amazing memories on our honeymoon"
      url: "https://buy.stripe.com/your-stripe-link"
      button_text: "Contribute to Honeymoon"
      icon: "✈️"
    - name: "Amazon Registry"
      description: "Traditional wedding gifts we'd love to receive"
      url: "https://www.amazon.com/wedding/registry/3SGD7UOZNH1VH"
      button_text: "View Amazon Registry"
      icon: "🎁"

# Photo gallery (optional)
gallery:
  images:
    - url: "./images/engagement-1.webp"
      thumbnail: "./images/engagement-1-thumb.webp"
      caption: "Engagement photos at Golden Gate Park"
      
    - url: "./images/engagement-2.webp"
      thumbnail: "./images/engagement-2-thumb.webp"
      caption: "At the beach"

# RSVP Configuration
rsvp:
  deadline: "2026-08-01"
  form_url: "https://docs.google.com/forms/d/e/1FAIpQLScQsp7KoNxn12-ouZytcb1TNE5TPzPNDbLf9508iZBKJtVZxA/viewform?embedded=true"


# Site metadata
site:
  title: "Mountain Wedding - Tye & Louise"
  description: "Join Tye & Louise for their mountain wedding celebration in Crested Butte, Colorado on September 12, 2026"
  author: "Tye & Louise"
  generator: "Wedding Site Builder v2.0"
  favicon_emoji: "🏔️"
  background_image: "./images/crested_butte.webp"
  
  # PWA settings
  pwa:
    name: "Tye & Louise Wedding"
    short_name: "Wedding"
    background_color: "#FEFEFE"
    theme_color: "#8B4513"

# Footer
footer:
  text: "Made with ❤️ by Tye and Louise"
  github_url: "https://github.com/tzasacky/wedding"
  github_text: "Make Your Own"
  stats_url: "./stats.html"
  stats_text: "Stats for Nerds"