# Wedding Site Configuration
# Edit this file to customize your wedding website

couple:
  names: "Tye & Louise"

date:
  display: "09.18.2026"
  iso: "2026-09-18T16:00:00"

theme:
  primary: "#781b12"         # Deep burgundy - warm and sophisticated
  font: "Montserrat"         # Clean mountain-appropriate font

  # Light theme - warm and elegant with your colors
  text_primary: "#2c1810"    # Very dark brown for better readability than pure black
  text_secondary: "#781b12"  # Deep burgundy for secondary content
  text_muted: "#41512d"      # Deep olive for muted text
  text_light: "#ffffff"      # Pure white for light text

  # Dark theme - burgundy background with warm text palette
  dark:
    text_primary: "#ffffff"  # Pure white for main text - maximum contrast on burgundy
    text_secondary: "#f3912b" # Warm orange for headings and accents
    text_muted: "#e5e1e3"    # Light warm gray for subtle text
    text_light: "#000000"    # Pure black for contrast elements

# Navigation sections - customize order and visibility
sections:
  - id: home
    name: "Home"
    enabled: true
    
  - id: details
    name: "Details"
    enabled: true
    
  - id: story
    name: "Our Story"
    enabled: false
    
  - id: timeline
    name: "Timeline"
    enabled: true
    
  - id: travel
    name: "Travel"
    enabled: true
    
  - id: accommodations
    name: "Hotels"
    enabled: true
    
  - id: registry
    name: "Registry"
    enabled: true
    
  - id: gallery
    name: "Gallery"
    enabled: false
    
  - id: rsvp
    name: "RSVP"
    enabled: true

# Event details
ceremony:
  time: "4:00 PM"
  venue: "Mountain Wedding Garden"
  address: "911 Gothic Rd"
  city: "Crested Butte, CO 81225"
  dress_code: "Mountain Formal"

reception:
  time: "6:00 PM"
  venue: "TBD"
  address: "TBD"
  city: "Crested Butte, CO 81224"
  dress_code: "Evening Formal. Bring warm clothes for the evening"

dress_code: "Mountain Formal. \nBring warm clothes for the evening"

# Our Story section (optional)
story:
  content: |
    <p>We met at a coffee shop on a rainy Tuesday morning. What started as a 
    spilled latte turned into a conversation that lasted until closing time.</p>
    
    <p>Five years, countless adventures, and one perfect proposal later, 
    we're ready to say "I do" surrounded by our favorite people.</p>

# Timeline section (optional)
timeline:
  events:
    - date: "Summer 2017"
      title: "Adventures Begin"
      description: "Road trips and exploring the great outdoors together"
      images:
        - "./images/roadtrip2017.webp"
        - "./images/4pass_2.webp"

    - date: "Winter 2018"
      title: "Louise's first time in Aspen"
      description: "Hitting the slopes in Aspen - discovering our love for the mountains"
      images:
        - "./images/louise_aspen.webp"

    - date: "Aug 2021"
      title: "Moving in Together in Raleigh"
      description: "Moving in together and making a space that's truly ours"
      images:
        - "./images/move_in.webp"
        - "./images/twin_oaks.webp"

    - date: "Nov 2022"
      title: "Getting Poppy"
      description: "Thanksgiving gave us more to be thankful for than expected this year"
      images:
        - "./images/poppy1.webp"
        - "./images/poppy2.webp"

    - date: "December 2024"
      title: "The Proposal"
      description: "A surprise proposal at the Maroon Bells"
      images:
        - "./images/engagement.webp"

# Travel Information
travel:
  airports:
    - name: "Gunnison-Crested Butte Regional Airport"
      code: "GUC"
      distance_miles: 28
      drive_time: "30 minutes"
      cost_range: "$$$"
      flight_availability: "Limited"
      description: "Closest airport to Crested Butte. For these dates, only three daily flights on United from Denver. Book early!"
      airlines: ["United (3 daily flights from DEN)", "Seasonal only: May 22 - Oct 25, 2025"]
      
    - name: "Montrose Regional Airport"
      code: "MTJ"
      distance_miles: 65
      drive_time: "1 hour 30 minutes"
      cost_range: "$$"
      flight_availability: "Good"
      description: "Year-round flights with good availability. Scenic drive over mountain passes."
      airlines: ["United", "American", "Delta", "Alaska"]
      
    - name: "Denver International Airport"
      code: "DEN"
      distance_miles: 230
      drive_time: "4 hours"
      cost_range: "$"
      flight_availability: "Excellent"
      description: "Most flight options and best prices. Beautiful mountain drive but long journey."
      airlines: ["All major airlines"]
      
  driving_tips:
    - "Rental car recommended for mountain driving and local flexibility"
    - "Check weather and road conditions, especially in September/winter months"
    - "Mountain passes can be challenging - allow extra driving time"
    - "Limited gas stations between airports and Crested Butte"
    
  alternative_transport:
    - name: "Epic Mountain Express"
      description: "Shuttle service from Denver Airport to Crested Butte"
      cost: "$150-200 per person"
      duration: "5-6 hours"
      
    - name: "Colorado Mountain Express"
      description: "Private shuttles from Montrose and other airports"
      cost: "Varies by airport and group size"
      duration: "1.5-2 hours from Montrose"

# Accommodations
hotels:
  - name: "The Grand Lodge Crested Butte"
    address: "6 Emmons Loop"
    city: "Mount Crested Butte, CO 81225"
    rate: "$220/night"
    link: "https://www.grandlodgecrestedbutte.com"
    
  - name: "Elk Mountain Lodge"
    address: "129 Gothic Avenue"
    city: "Crested Butte, CO 81224"
    rate: "$180/night"
    link: "https://www.elkmountainlodge.net"
    
  - name: "Old Town Inn"
    address: "708 6th Street"
    city: "Crested Butte, CO 81224"
    rate: "$160/night"
    link: "https://www.oldtowninn.net"

# Registry
registry:
  message: "Your presence at our wedding is the greatest gift of all. However, if you wish to honor us with a gift, we've registered at the following stores."
  stores:
    - name: "Honeymoon Fund"
      payment_options:
        - name: "Honeyfund"
          url: "https://www.honeyfund.com/site/zasacky-lindegaard-09-18-2026"
    - name: "Amazon"
      url: "https://www.amazon.com/wedding/registry/3SGD7UOZNH1VH"

# Photo gallery (optional)
gallery:
  images:
    - url: "./images/engagement-1.webp"
      thumbnail: "./images/engagement-1-thumb.webp"
      caption: "Engagement photos at Golden Gate Park"
      
    - url: "./images/engagement-2.webp"
      thumbnail: "./images/engagement-2-thumb.webp"
      caption: "At the beach"

# RSVP Configuration
rsvp:
  deadline: "2026-08-01"
  form_url: "https://docs.google.com/forms/d/e/1FAIpQLScQsp7KoNxn12-ouZytcb1TNE5TPzPNDbLf9508iZBKJtVZxA/viewform?embedded=true"


# Footer
footer:
  text: "Made with ❤️ by Tye"
  github_url: "https://github.com/tzasacky/wedding"